// Discovery-value classification: could the brand have found this post themselves?
//
// THE POINT OF THE WHOLE TOOL
// Anyone can follow #stelz on Instagram for free. So a post carrying the brand
// hashtag has close to zero marginal value here. What this tool uniquely finds
// is content where the can is visible in the PIXELS but the post carries no
// brand hashtag and no @mention — content the brand could never have surfaced
// on their own.
//
// This is a restored regression, not a new idea. The legacy dashboard had a
// "Visual only (no tag/hashtag)" filter (dashboard/index.html:1250, classifier
// at :894-908), mirroring classify_signal() in
// tools/stelz_brand_watch/23_auto_report.py:69-81. The React rewrite dropped it.
//
// WHY THIS CAN RUN CLIENT-SIDE
// Nothing in the backend records which hashtag scrape surfaced a post — the tag
// is in the caller's scope at scan_hashtags.py:292 and never written. But we
// don't need it. "Which scrape found this" is the wrong question; "could the
// brand have found this themselves" is the right one, and that is answerable
// from post_hashtags + post_mentions, both already denormalized onto every
// detection (detect_image.py:51-69) and neither truncated.

import type { DetectionRow } from './types'

export type Signal = 'brand_owned' | 'hashtag' | 'mention' | 'visual_only'

export type SignalInfo = {
  signal: Signal
  /** Could the brand have found this on Instagram without this tool? */
  findable: boolean
  /** Which brand tags/mentions matched — for explaining the verdict in the UI. */
  matched: string[]
  /**
   * Brand name appears in the caption prose. DISPLAY ONLY — deliberately does
   * NOT affect `signal`. See the caption note below.
   */
  namedInCaption: boolean
}

export type SignalInput = Pick<
  DetectionRow,
  'creator_handle' | 'post_hashtags' | 'post_mentions' | 'post_caption'
>

// Stelz' own accounts + distributors. Transcribed from 23_auto_report.py:72.
// Exact-match only, never a heuristic: "handle contains stelz" would classify a
// fan account like @stelzlover as brand-owned and hide their content, which is
// the precise opposite of what this tool is for.
export const BRAND_OWNED_HANDLES = new Set([
  'drinkstelz',
  'stelz_suriname',
  'bullseyedistribution',
  'stanbev_international',
  'bavaria.bierkoerier',
  'stelzofficial',
])

// Generated by firebase/functions/lib/hashtags.py stelz_pool('instagram'),
// families brand_core + product_line + flavour + brand_event. Regenerate with:
//   python3 -c "import sys; sys.path.insert(0,'firebase/functions'); \
//     from lib import hashtags; print(sorted(t['tag'] for t in \
//     hashtags.stelz_pool('instagram') if t['family'] in \
//     ('brand_core','product_line','flavour','brand_event')))"
const BRAND_TAGS = new Set([
  'casastelz', 'drinkstelz', 'stelz', 'stelzbeuk', 'stelzcassis', 'stelzcheck',
  'stelzdrinks', 'stelzfest', 'stelzhardicedtea', 'stelzhardlemonade',
  'stelzhardseltzer', 'stelzhouse', 'stelzibiza', 'stelzint', 'stelzlemon',
  'stelzlime', 'stelzmango', 'stelzmixedclassics', 'stelznl', 'stelzofficial',
  'stelzparty', 'stelzpeach', 'stelzraspberry', 'stelzsummer', 'stelzworld',
  'teamstelz', 'thisisstelz',
])

// The stelz* subset of identity.COMMON_WORD_DENYLIST. German "Stelzlager"
// (a terrace pedestal) is the real regression that got OCR removed from the
// detection pipeline entirely — see firebase/functions/lib/identity.py.
const NON_BRAND_TAGS = new Set([
  'stelzlager', 'stelzlagern', 'stelzen', 'stelze', 'stelzenlaufer',
  'stelzenlauferin', 'stelzvogel', 'stelzer', 'stelzl',
])

// Dutch stilt-walking compounds (#stelzenlopen, #stelzenlopers, #stelzenlaufer)
// that exact-token matching in NON_BRAND_TAGS would miss.
const NON_BRAND_PREFIXES = ['stelzen', 'stelzlager']

/** Lowercase + strip diacritics. Mirrors identity.normalize(). STËLZ -> stelz. */
export function normalize(s: string | null | undefined): string {
  if (!s) return ''
  return s.normalize('NFD').replace(/[̀-ͯ]/g, '').toLowerCase().trim()
}

/**
 * Is this hashtag a brand tag — i.e. one that makes the post findable on
 * Instagram without this tool?
 *
 * Three gates, and the ORDER IS LOAD-BEARING. The allowlist must run first
 * because #stelzlime and #stelzlemon are real flavour tags that collide with
 * the stelzlager/stelzen denylist family.
 *
 * Gate 3 uses a PREFIX, not a substring, unlike identity.is_brand_specific_tag.
 * That function documents substring matching as safe because a false positive
 * there costs one wrongly-promoted creator. Here the cost is inverted: a false
 * brand-tag match HIDES a genuinely untagged post from the primary view — which
 * is exactly the complaint this module exists to fix, in reverse.
 */
export function isBrandTag(tag: string): boolean {
  const t = normalize(tag).replace(/^#/, '')
  if (!t) return false
  if (BRAND_TAGS.has(t)) return true                                  // 1
  if (NON_BRAND_TAGS.has(t)) return false                             // 2
  if (NON_BRAND_PREFIXES.some((p) => t.startsWith(p))) return false
  return t.startsWith('stelz')                                        // 3
}

function isBrandMention(mention: string): boolean {
  // scan_hashtags.py:825 writes mentions raw-case (unlike hashtags, which are
  // lowercased at write), so normalizing here is required, not cosmetic.
  return BRAND_OWNED_HANDLES.has(normalize(mention).replace(/^@/, ''))
}

// Word-boundary brand match for free text — the TS mirror of
// identity.has_brand_word. Built once at module scope. Used ONLY for the
// namedInCaption display badge, never for the findability decision.
const CAPTION_BRAND_RE = /(?:^|[^a-z0-9])(stelz|stelzz|stellz|steelz)(?![a-z0-9])/

function isNamedInCaption(caption: string | null | undefined): boolean {
  const n = normalize(caption)
  if (!n) return false
  // "Stelzlager gemonteerd" must not count. The lookahead in the regex already
  // rejects it, but the denylist check makes the intent explicit and survives
  // future edits to the pattern.
  const tokens = n.match(/[a-z0-9]+/g) ?? []
  if (tokens.length && tokens.every((t) => NON_BRAND_TAGS.has(t))) return false
  return CAPTION_BRAND_RE.test(n)
}

/**
 * Classify one detection by how findable its post was without this tool.
 *
 * Precedence mirrors the legacy Python classifier:
 *   brand_owned > hashtag > mention > visual_only
 *
 * THE CAPTION IS DELIBERATELY NOT PART OF THIS DECISION, which is where we
 * diverge from classify_signal(). Two reasons:
 *
 *  1. post_caption is truncated to 500 chars on the detection doc
 *     (detect_image.py:66) while the post itself holds 2000, and Dutch
 *     Instagram captions put hashtags at the END. It is the one field that
 *     systematically lies in the direction that matters.
 *
 *  2. Instagram has no full-text caption search. A caption reading "lekker
 *     glaasje stelz" with no hashtag and no mention is genuinely NOT findable
 *     by the brand. Counting it as findable would understate our own value.
 *
 * post_hashtags and post_mentions are complete and untruncated, and they are
 * exactly the two things Instagram itself indexes — which is also the
 * defensible line in a sales conversation.
 */
export function classifySignal(d: SignalInput): SignalInfo {
  const namedInCaption = isNamedInCaption(d.post_caption)

  if (BRAND_OWNED_HANDLES.has(normalize(d.creator_handle))) {
    return { signal: 'brand_owned', findable: true, matched: [normalize(d.creator_handle)], namedInCaption }
  }

  let tags = d.post_hashtags ?? []
  // TikTok rescue: lib/tiktok_scraper.py:66 hardcodes "hashtags": [], so tags
  // can live only inside the caption text. This can ONLY add tags, so it can
  // only move a post untagged -> tagged. It errs conservative and can never
  // inflate the untagged headline number.
  if (!tags.length && d.post_caption?.includes('#')) {
    tags = [...(normalize(d.post_caption).match(/#([a-z0-9_]+)/g) ?? [])].map((t) => t.slice(1))
  }

  const matchedTags = tags.filter(isBrandTag)
  if (matchedTags.length) {
    return { signal: 'hashtag', findable: true, matched: matchedTags, namedInCaption }
  }

  const matchedMentions = (d.post_mentions ?? []).filter(isBrandMention)
  if (matchedMentions.length) {
    return { signal: 'mention', findable: true, matched: matchedMentions, namedInCaption }
  }

  return { signal: 'visual_only', findable: false, matched: [], namedInCaption }
}

/** Annotate rows in place-ish (returns new objects). Call once, after dedupe. */
export function withSignal<T extends DetectionRow>(rows: T[]): T[] {
  return rows.map((r) => ({ ...r, signal: classifySignal(r) }))
}

/** Counts per class, for KPIs and the view switch. */
export function signalCounts(rows: DetectionRow[]): Record<Signal, number> {
  const out: Record<Signal, number> = { visual_only: 0, hashtag: 0, mention: 0, brand_owned: 0 }
  for (const r of rows) out[r.signal?.signal ?? classifySignal(r).signal]++
  return out
}

/**
 * The headline number: share of hits the brand could NOT have found themselves.
 *
 * Brand-owned posts are excluded from the denominator — the brand's own content
 * is not a discovery either way, and leaving it in dilutes the percentage.
 *
 * Honest framing note for whoever writes the UI copy: scanning is hashtag-
 * seeded, so this share is structurally suppressed by how discovery currently
 * works. "X% of all Stelz content on Instagram is untagged" would be FALSE.
 * The defensible claim is "X% of the hits in your dashboard carry no #stelz
 * and no @stelz".
 */
export function untaggedShare(rows: DetectionRow[]): { untagged: number; total: number; pct: number } {
  const c = signalCounts(rows)
  const total = c.visual_only + c.hashtag + c.mention
  return { untagged: c.visual_only, total, pct: total ? Math.round((c.visual_only / total) * 100) : 0 }
}

/**
 * Dev-only sanity report over the cached dashboard data. Attached to
 * `window.signalReport` in dev builds (see main.tsx); run it in the browser
 * console after the dashboard has loaded once.
 *
 * This is the check that decides whether the untagged-first UI is worth
 * anything: if untagged hits number in the low tens, the dashboard is not the
 * problem, the discovery strategy is. It also guards the headline claim — a
 * reading near 99% or near 5% means the CLASSIFIER is wrong, not the data.
 */
export function signalReport(rows: DetectionRow[]): void {
  const real = rows.filter((r) => r.is_false_positive !== true)
  const counts = signalCounts(real)
  const share = untaggedShare(real)

  // A missing postHashtags field reads falsy and would be silently counted as
  // untagged, inflating the headline. Legacy docs predate detect_image's
  // denormalization, so this must be reported, not assumed to be zero.
  const missing = real.filter((r) => r.post_hashtags == null).length

  console.log('%c— discovery signal mix —', 'font-weight:bold')
  console.table(counts)
  console.log(`untagged share: ${share.untagged}/${share.total} = ${share.pct}%`,
    share.pct >= 60 && share.pct <= 90 ? '(within the expected 60-90% band)'
      : '(OUTSIDE the expected band — suspect the classifier, not the data)')
  if (missing) {
    console.warn(`${missing} rows have no post_hashtags field at all (legacy docs). ` +
      `They currently count as untagged; exclude them from the headline if this is a large share.`)
  }
  console.log('sample untagged rows:', real
    .filter((r) => (r.signal?.signal ?? classifySignal(r).signal) === 'visual_only')
    .slice(0, 10)
    .map((r) => ({ handle: r.creator_handle, tags: r.post_hashtags, url: r.post_url })))
}
